language: general
sudo: required
services:
  - docker

before_install:
  - docker build -t nkwametuffour/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true nkwametuffour/docker-react-app npm test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-889072342953"
  bucket_path: "docker-react-app"
  on:
    branch: main
